"""
Unity IL2CPP Hybrid Engine Adapter for GameStringer CLI.

Combines static Unity Asset string extraction (UnityPy) with global-metadata.dat
string literal extraction, IL2CppDumper integration, strict human-text filtering,
XLIFF categorization, and BepInEx/XUnity.AutoTranslator pre-translation generation.

Ensures zero text is missed:
- Asset strings are statically repatched in asset files.
- Metadata/code strings are pre-translated into BepInEx/Translation/<lang>/Text/_AutoGeneratedTranslations.txt
  to provide instant pre-translated runtime translation without touching native GameAssembly.dll binaries.
"""

import os
import re
import shutil
import struct
import subprocess
import json
from typing import List, Optional, Tuple, Dict, Any
from gamestringer.core.base_engine import BaseEngine, TransUnit, validate_smart_tokens
from gamestringer.core.xliff_exporter import export_xliff, parse_xliff
from gamestringer.core.backup import create_backup
from gamestringer.core.logger import logger
from gamestringer.engines.unity_mono import UnityMonoEngine

IL2CPP_METADATA_MAGIC = 0xFAB11BAF
IL2CPPDUMPER_URL = "https://github.com/Perfare/Il2CppDumper/releases"

# Namespace & Code Class Exclusions
NAMESPACE_PREFIXES = (
    "System.", "UnityEngine.", "Unity.", "Microsoft.", "Mono.", "Google.",
    "Newtonsoft.", "AccelByte.", "Assembly-CSharp", "AssemblyCSharp", "EOSSDK", "EOS",
    "Steam.", "Epic.", "TMPro.", "FMOD.", "Spine.", "Oculus.", "Photon.",
    "Blackrazor.", "Il2Cpp", "Zenject.", "UniTask.", "NaughtyAttributes."
)

UI_WHITELIST = {
    "ok", "yes", "no", "cancel", "back", "play", "start", "quit", "exit",
    "save", "load", "settings", "options", "inventory", "map", "quest", "quests",
    "achievements", "credits", "continue", "new game", "load game", "main menu",
    "pause", "resume", "retry", "skip", "confirm", "delete", "rename",
    "attack", "defend", "item", "magic", "skill", "status", "equip", "unequip",
    "buy", "sell", "talk", "inspect", "use", "take", "drop", "combine",
    "north", "south", "east", "west", "up", "down", "left", "right",
    "locked", "unlocked", "new", "rare", "epic", "legendary", "common",
    "hp", "mp", "sp", "xp", "lv", "level", "gold", "silver", "bronze",
    "easy", "normal", "hard", "extreme", "difficulty",
    "on", "off", "enabled", "disabled", "active", "inactive",
    "solo", "coop", "multiplayer", "online", "offline",
    "male", "female", "other", "unknown",
    "strength", "dexterity", "intelligence", "vitality", "luck",
    "warrior", "mage", "rogue", "cleric", "archer", "paladin",
    "sword", "shield", "bow", "staff", "armor", "helmet", "boots", "gloves",
    "potion", "ether", "antidote", "phoenix", "elixir",
    "fire", "ice", "lightning", "water", "earth", "wind", "light", "dark",
    "tutorial", "hint", "tip", "warning", "error", "success", "failed",
    "chapter", "stage", "wave", "round", "turn", "time", "score", "combo",
    "friend", "party", "guild", "clan", "team", "rival", "enemy", "boss",
    "craft", "smith", "shop", "store", "bank", "inn", "temple", "dungeon",
    "world", "realm", "kingdom", "empire", "village", "city", "forest", "cave",
    "mountain", "river", "lake", "ocean", "desert", "swamp", "tundra",
    "day", "night", "morning", "evening", "dawn", "dusk", "sun", "moon",
    "spring", "summer", "autumn", "winter",
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
    "monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday",
}

DOT_CLASS_RE = re.compile(r"[A-Z][a-zA-Z0-9_]+\.[A-Z][a-zA-Z0-9_]+")
METHOD_JUNK_RE = re.compile(r"<.+>|@.+::|^\w+/\w+|^[a-zA-Z0-9_]+=[a-zA-Z0-9_]+")
GUID_RE = re.compile(r"^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$|^[0-9a-fA-F]{32}$")
HEX_RE = re.compile(r"^[0-9a-fA-F]{16,}$")
REPEAT_RE = re.compile(r"^(.)\1{2,}$")
NUM_RE = re.compile(r"^\d+$")
FILE_EXT_RE = re.compile(r"\.(dll|cs|exe|asset|bundle|so|dylib|unity3d|pdb|png|jpg|wav|mp3|ogg)$", re.IGNORECASE)
SYMBOL_NOISE_RE = re.compile(r"^[@#$%^&*()_+={}\[\]|\\:;<>/\~`\x00-\x1f]+$")
ALPHA_RE = re.compile(r"[a-zA-Z\u00C0-\u024F\u0400-\u04FF\u4E00-\u9FFF]")
PUNCT_RE = re.compile(r"[.,!?;:]")


def find_il2cppdumper_path(custom_path: Optional[str] = None) -> Optional[str]:
    """
    Search for IL2CppDumper executable across custom path, PATH, and common system locations.
    """
    if custom_path:
        abs_custom = os.path.abspath(custom_path)
        if os.path.exists(abs_custom):
            return abs_custom
        elif os.path.isdir(custom_path):
            exe_cand = os.path.join(custom_path, "IL2CppDumper.exe" if os.name == "nt" else "IL2CppDumper")
            if os.path.exists(exe_cand):
                return exe_cand

    # Check system PATH
    which_bin = shutil.which("IL2CppDumper.exe") or shutil.which("IL2CppDumper") or shutil.which("il2cppdumper")
    if which_bin:
        return which_bin

    # Common system locations
    candidates = []
    if os.name == "nt":
        candidates.extend([
            r"C:\Tools\IL2CppDumper\IL2CppDumper.exe",
            os.path.expandvars(r"%USERPROFILE%\Tools\IL2CppDumper\IL2CppDumper.exe"),
            os.path.expandvars(r"%LOCALAPPDATA%\IL2CppDumper\IL2CppDumper.exe"),
            os.path.abspath("./tools/IL2CppDumper/IL2CppDumper.exe"),
            os.path.abspath("../tools/IL2CppDumper/IL2CppDumper.exe"),
        ])
    else:
        candidates.extend([
            os.path.expanduser("~/tools/IL2CppDumper/IL2CppDumper"),
            os.path.expanduser("~/.local/bin/IL2CppDumper"),
            os.path.abspath("./tools/IL2CppDumper/IL2CppDumper"),
        ])

    for cand in candidates:
        if os.path.exists(cand) and os.path.isfile(cand):
            return cand

    return None


_ASSEMBLY_QUALIFIED_RE = re.compile(
    r",\s*Version=[\d.]+,\s*Culture=\w+,\s*PublicKeyToken=(?:null|[0-9a-fA-F]+)", re.IGNORECASE
)
_DOTTED_SEGMENT_RE = re.compile(r"^[A-Z][A-Za-z0-9_\-]*$")


def _looks_like_type_reference(s: str) -> bool:
    """True if string is a serialized C# type or assembly reference (e.g. 'PlayerDefaultState, Assembly-CSharp')."""
    if _ASSEMBLY_QUALIFIED_RE.search(s):
        return True
    segments = [seg.strip() for seg in re.split(r"[.,]", s)]
    if len(segments) >= 2 and all(seg for seg in segments):
        return all(_DOTTED_SEGMENT_RE.match(seg) for seg in segments)
    return False


def clean_control_chars(s: str) -> str:
    """Strip binary non-printable control characters and lone surrogates from text."""
    if not s:
        return ""
    return re.sub(r"[\x00-\x08\x0b\x0c\x0e-\x1f\x7f-\x9f\ud800-\udfff]", "", s).strip()


def should_keep_metadata_string(s: str, class_context: str = "") -> bool:
    """
    Determine whether a metadata string literal should be kept or filtered out as garbage.
    Applies strict human-text filtering with a safety net for single UI words (Title Case / ALL CAPS)
    and a UI word whitelist.
    """
    s = clean_control_chars(s)
    if not s or len(s) < 2:
        return False

    has_spaces = " " in s

    if METHOD_JUNK_RE.search(s) and not has_spaces:
        return False

    if REPEAT_RE.match(s) or NUM_RE.match(s) or SYMBOL_NOISE_RE.match(s):
        return False

    if not ALPHA_RE.search(s):
        return False

    # Structural Type/Assembly Reference Exclusion
    if _looks_like_type_reference(s) and not has_spaces:
        return False

    # Namespace & Code Class Exclusions
    if any(s.startswith(p) or f".{p}" in s or s.lower().startswith(p.lower()) for p in NAMESPACE_PREFIXES):
        return False

    # Dotted Class / Namespace pattern (e.g. AccelByte.Sdk.Core, UnityEngine.Rendering)
    if DOT_CLASS_RE.search(s) and not has_spaces:
        return False

    if FILE_EXT_RE.search(s):
        return False

    if GUID_RE.match(s) or HEX_RE.match(s):
        return False

    # Excessive symbol ratio filter (>30% symbols)
    symbols_count = sum(1 for c in s if c in "@#$%^&*()_+={}[]|\\:;<>/\x7e`")
    if len(s) > 0 and (symbols_count / len(s)) > 0.30 and not has_spaces:
        return False

    s_clean_lower = s.lower().strip()

    # 1. UI Whitelist Check (case-insensitive exact match)
    if s_clean_lower in UI_WHITELIST:
        return True

    # 2. Safety Net Rule for single UI words:
    # - 2-20 characters long
    # - ONLY letters (A-Z, a-z) — no numbers, no underscores, no dots
    # - Title Case (first letter uppercase, rest lowercase) OR ALL CAPS
    if 2 <= len(s) <= 20 and re.match(r"^[a-zA-Z]+$", s):
        is_title_case = s[0].isupper() and (len(s) == 1 or s[1:].islower())
        is_all_caps = s.isupper()
        if is_title_case or is_all_caps:
            return True

    # 3. Standard Strict Rule for multi-word or rich human text:
    has_accented = bool(re.search(r"[^\x00-\x7F]", s))
    has_sentence_punct = bool(PUNCT_RE.search(s))

    ctx_lower = class_context.lower()
    is_ui_ctx = any(k in ctx_lower for k in ("ui", "text", "localization", "menu", "quest", "label", "dialogue"))

    if has_spaces or has_accented or (has_sentence_punct and len(s) >= 4 and ALPHA_RE.search(s)) or is_ui_ctx:
        return True

    return False


def determine_category(s: str, class_context: str = "") -> str:
    """
    Categorize a string entry into 'ui', 'dialogue', 'system', or 'unknown'.
    """
    ctx_lower = class_context.lower()
    s_lower = s.lower()

    if any(k in ctx_lower for k in ("ui", "text", "localization", "menu", "button", "hud", "label", "view")) or any(s_lower.startswith(prefix) for prefix in ("btn_", "lbl_", "txt_", "ui_")):
        return "ui"

    if any(k in ctx_lower for k in ("dialogue", "npc", "quest", "story", "chat", "talk", "narrat")) or '"' in s or "'" in s or s.endswith((".", "!", "?")):
        return "dialogue"

    if any(k in ctx_lower for k in ("system", "engine", "manager", "network", "config", "setting", "audio", "video", "save")):
        return "system"

    return "unknown"


class IL2CppHybridEngine(BaseEngine):

    def __init__(self):
        self._unity_mono = UnityMonoEngine()

    @property
    def name(self) -> str:
        return "il2cpp"

    @property
    def description(self) -> str:
        return "Unity IL2CPP Hybrid Engine (Assets + BepInEx/XUnity Pre-translation)"

    @property
    def supported_extensions(self) -> List[str]:
        return [".dat", ".dll", ".so", ".bundle", ".assets"]

    def detect(self, input_path: str) -> bool:
        if not os.path.exists(input_path):
            return False

        meta_path, dll_path = self._find_il2cpp_files(input_path)
        return meta_path is not None and dll_path is not None

    def extract(self, input_path: str, output_xliff_path: str, dry_run: bool = False, il2cppdumper_path: Optional[str] = None) -> str:
        meta_path, dll_path = self._find_il2cpp_files(input_path)
        if meta_path is None or dll_path is None:
            raise ValueError(f"Target path '{input_path}' is not a valid IL2CPP game directory (missing GameAssembly.dll or global-metadata.dat).")

        units: List[TransUnit] = []
        counter = 0

        # SOURCE A: Unity Assets extraction (.assets / .bundle)
        try:
            asset_xliff_tmp = output_xliff_path + ".asset_tmp"
            self._unity_mono.extract(input_path, asset_xliff_tmp, dry_run=False)
            if os.path.exists(asset_xliff_tmp):
                asset_units = parse_xliff(asset_xliff_tmp)
                for u in asset_units:
                    u.context_note = f"source:asset | category:{determine_category(u.source, u.context_note or '')} | {u.context_note or ''}"
                    units.append(u)
                os.remove(asset_xliff_tmp)
        except Exception as err:
            logger.warning(f"Skipping corrupt or unreadable asset files during IL2CPP extract: {err}")

        # SOURCE B: global-metadata.dat extraction (with IL2CppDumper or Strict Human Text Fallback)
        meta_units, counter = self._extract_metadata_strings(meta_path, dll_path, counter, il2cppdumper_path=il2cppdumper_path)
        units.extend(meta_units)

        summary = f"Scanned IL2CPP assets and metadata, found {len(units)} filtered string(s)."

        if dry_run:
            logger.info(f"[DRY-RUN] {summary} No XLIFF file written.")
            return f"[DRY-RUN] {summary}"

        if not units:
            raise ValueError(f"No text entries could be extracted from IL2CPP assets or metadata. {summary}")

        export_xliff(
            units=units,
            output_path=output_xliff_path,
            source_lang="en",
            target_lang="it",
            engine_name=self.name,
        )
        logger.info(f"Extracted IL2CPP strings saved to: {output_xliff_path}")
        return f"Extracted {len(units)} string(s) to '{output_xliff_path}'. {summary}"

    def patch(self, input_path: str, xliff_path: str, output_path: Optional[str] = None) -> str:
        units = parse_xliff(xliff_path)
        if not units:
            raise ValueError(f"No translatable units found in XLIFF file: {xliff_path}")

        translated_units = [u for u in units if u.target and u.target.strip()]
        if not translated_units:
            return "No target translations found in XLIFF to patch."

        # Validate Smart String tokens before patching
        for u in translated_units:
            missing_tokens = validate_smart_tokens(u.source, u.target)
            if missing_tokens:
                logger.warning(f"Smart token mismatch in unit [{u.id}]: missing tokens {missing_tokens}. Proceeding with patch.")

        # Separate TARGET A (Assets) and TARGET B (Metadata Strings)
        asset_units = []
        metadata_units = []

        for u in translated_units:
            note = u.context_note or ""
            if "source:asset" in note:
                asset_units.append(u)
            else:
                metadata_units.append(u)

        game_root = os.path.abspath(input_path)
        if os.path.isfile(game_root):
            game_root = os.path.dirname(game_root)

        patched_messages = []

        # TARGET A: Repatch asset strings in-place using UnityMono engine
        if asset_units:
            asset_xliff_tmp = xliff_path + ".asset_patch_tmp"
            export_xliff(asset_units, asset_xliff_tmp, engine_name="unity")
            try:
                asset_msg = self._unity_mono.patch(input_path, asset_xliff_tmp, output_path)
                patched_messages.append(asset_msg)
            finally:
                if os.path.exists(asset_xliff_tmp):
                    os.remove(asset_xliff_tmp)

        # TARGET B: Generate XUnity.AutoTranslator pre-translation files for metadata strings
        if metadata_units:
            target_lang = "it"
            target_dir = output_path if output_path else game_root
            bepinex_dir = os.path.join(target_dir, "BepInEx", "Translation", target_lang, "Text")
            os.makedirs(bepinex_dir, exist_ok=True)

            auto_trans_file = os.path.join(bepinex_dir, "_AutoGeneratedTranslations.txt")

            lines = [
                f"# GameStringer CLI — Pre-translated IL2CPP Metadata Strings for '{target_lang}'",
                f"# Copy this BepInEx folder to game root directory for instant runtime translation.",
                "",
            ]

            seen_meta = set()
            for u in metadata_units:
                src_str = u.source.replace("\r", "").replace("\n", "\\n")
                tgt_str = u.target.replace("\r", "").replace("\n", "\\n")
                if src_str and tgt_str and src_str not in seen_meta:
                    seen_meta.add(src_str)
                    lines.append(f'sr:"{src_str}"="{tgt_str}"')

            with open(auto_trans_file, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))

            readme_path = os.path.join(target_dir, "README_IL2CPP_SETUP.md")
            readme_content = f"""# GameStringer IL2CPP Runtime Setup Guide

Your translations for IL2CPP metadata strings have been saved into:
`BepInEx/Translation/{target_lang}/Text/_AutoGeneratedTranslations.txt`

## Recommended Installation Steps:
1. Download & Install **BepInEx 6 IL2CPP** (v6.0.0-pre.2 or newer) into your game root folder.
2. Download & Install **XUnity.AutoTranslator-BepInEx-IL2CPP** plugin into `BepInEx/plugins/`.
3. Copy the generated `BepInEx/` directory into your game root folder.
4. Launch the game. XUnity.AutoTranslator will automatically load your pre-translated strings from `_AutoGeneratedTranslations.txt` with zero delay and no live API costs!
"""
            with open(readme_path, "w", encoding="utf-8") as f:
                f.write(readme_content)

            patched_messages.append(
                f"Generated XUnity pre-translation file ({len(seen_meta)} entries) at BepInEx/Translation/{target_lang}/Text/_AutoGeneratedTranslations.txt and README_IL2CPP_SETUP.md"
            )

        return "IL2CPP Hybrid patch complete. " + " | ".join(patched_messages)

    # ─────────────────────────────────────────────────────────────
    # INTERNAL HELPERS
    # ─────────────────────────────────────────────────────────────

    def _find_il2cpp_files(self, input_path: str) -> Tuple[Optional[str], Optional[str]]:
        abs_path = os.path.abspath(input_path)
        game_dir = os.path.dirname(abs_path) if os.path.isfile(abs_path) else abs_path

        meta_path = None
        dll_path = None

        for candidate in ("GameAssembly.dll", "libil2cpp.so", "GameAssembly.so"):
            p = os.path.join(game_dir, candidate)
            if os.path.isfile(p):
                dll_path = p
                break

        direct_meta = os.path.join(game_dir, "il2cpp_data", "Metadata", "global-metadata.dat")
        if os.path.isfile(direct_meta):
            meta_path = direct_meta
        else:
            for root, _, files in os.walk(game_dir):
                if "global-metadata.dat" in files:
                    meta_path = os.path.join(root, "global-metadata.dat")
                    break

        return meta_path, dll_path

    def _extract_metadata_strings(self, meta_path: str, dll_path: str, start_counter: int, il2cppdumper_path: Optional[str] = None) -> Tuple[List[TransUnit], int]:
        units: List[TransUnit] = []
        counter = start_counter

        dumper_bin = find_il2cppdumper_path(il2cppdumper_path)

        if dumper_bin:
            logger.info(f"Using IL2CppDumper executable: '{dumper_bin}'...")
            try:
                out_dir = meta_path + "_dumper_out"
                os.makedirs(out_dir, exist_ok=True)
                subprocess.run([dumper_bin, dll_path, meta_path, out_dir], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                json_file = os.path.join(out_dir, "stringliteral.json")
                if os.path.exists(json_file):
                    with open(json_file, "r", encoding="utf-8") as f:
                        data = json.load(f)

                    for item in data:
                        val = item.get("value") or item.get("string") or item.get("str")
                        class_ctx = item.get("type") or item.get("name") or item.get("class") or ""

                        if val and should_keep_metadata_string(val, class_context=class_ctx):
                            counter += 1
                            category = determine_category(val, class_context=class_ctx)
                            units.append(TransUnit(
                                id=f"il2cpp_meta_{counter:06d}",
                                source=clean_control_chars(val),
                                file_path="global-metadata.dat",
                                context_note=f"source:metadata | via:IL2CppDumper | category:{category} | class:{class_ctx}",
                            ))

                    shutil.rmtree(out_dir, ignore_errors=True)
                    if units:
                        return units, counter
            except Exception as err:
                logger.warning(f"IL2CppDumper execution failed: {err}. Falling back to pure-Python metadata reader.")

        # Log clear warning when IL2CppDumper is not installed
        logger.warning(
            f"IL2CppDumper not found. Falling back to pure-Python metadata reader with strict human-text filters.\n"
            f"Download IL2CppDumper for enhanced class/method context from: {IL2CPPDUMPER_URL}"
        )

        # Pure Python fallback with Strict Human Text Filtering
        try:
            with open(meta_path, "rb") as f:
                data = f.read()

            if len(data) >= 8:
                magic, version = struct.unpack_from("<II", data, 0)
                if magic == IL2CPP_METADATA_MAGIC:
                    null_chunks = data.split(b"\x00")
                    seen = set()
                    for raw in null_chunks:
                        raw_str = raw.strip()
                        if len(raw_str) >= 2:
                            try:
                                s = clean_control_chars(raw_str.decode("utf-8", errors="ignore"))
                                if should_keep_metadata_string(s) and s not in seen:
                                    seen.add(s)
                                    counter += 1
                                    category = determine_category(s)
                                    units.append(TransUnit(
                                        id=f"il2cpp_meta_{counter:06d}",
                                        source=s,
                                        file_path="global-metadata.dat",
                                        context_note=f"source:metadata | version:{version} | category:{category}",
                                    ))
                            except Exception:
                                pass
        except Exception as err:
            logger.warning(f"Error extracting metadata strings from '{meta_path}': {err}")

        return units, counter
